services:
  app:
    container_name: go-mail-automation
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
volumes:
  postgres_data:
